#!./perl.static -w

#
# Fix up generated .ph files
#

use strict;
use File::Find;

my @args = @ARGV;
@ARGV = ();
find sub { push @ARGV, $File::Find::name if -f and /\.ph$/ }, @args;

$^I = '';

die "$0: no headers under @args?\n" unless @ARGV;
while (<>)
{
    # discard casts
    s/(?<!\$sizeof\{)(&__const\s+)?\\'struct[^\\']+\\'[^;]*;/1;/g;
    s/'char'\[\d+\]/1/g;

    print;
}
