#!./perl.static -w

#
# Create perlapi-<ver> provides substvar
#

BEGIN { unshift @INC, 'lib' }
use strict;
use Config;

print +(join ', ', map "perlapi-$_",
	sort $Config{version},
	grep /^[0-9.]+$/,
	split ' ', $Config{inc_version_list}), "\n";
