#----------------------------------------------------------------------
#                     Makefile to build linotify
#                 Copyright (c) 2015 American Megatrends Inc 
#-----------------------------------------------------------------------

#------- Comment/uncomment the following line to enable/disable debugging------
DEBUG 		= n
#------------------------------------------------------------------------------

#---------------------- Change according to your files ------------------------
LIBRARY_NAME	= inotify
SRC		=  linotify.c

CFLAGS += -I${TARGETDIR}/usr/include/lua5.1
CFLAGS += -I${TARGETDIR}/usr/include/${MULTI_ARCH_LIB}

include ${TOOLDIR}/rules/Rules.make.libs
#------------------------------------------------------------------------------


