#----------------------------------------------------------------------
#                      Makefile to build libcrc32c
#                 Copyright (c) 2018 American Megatrends Inc 
#-----------------------------------------------------------------------

#------- Comment/uncomment the following line to enable/disable debugging--------------
DEBUG = n
#---------------------------------------------------------------------------------------
#---------always set target as below if you are part of libami---------------------------
LIBRARY_NAME 	= libcrc32c
#----------------------------------------------------------------------------------------
#---------------------- Change according to your files ----------------------------------
SRC 		= crc32c.c	 	    # Source File

include ${TOOLDIR}/rules/Rules.make.libs

