#!/bin/sh
# autopkgtest check: Build and run a simple program against libstdc++,
# to verify basic compile-time and run-time linking functionality.

set -e

CXX=g++-8

WORKDIR=$(mktemp -d)
trap "rm -rf $WORKDIR" 0 INT QUIT ABRT PIPE TERM
cd $WORKDIR
cat <<EOF > libstdcxx.cc
#include <iostream>
using namespace std;

int main() {
 cout << "Hello! World!\n";
 return 0;
}
EOF

$CXX -o cxxtest libstdcxx.cc
echo "build: OK"
ldd cxxtest
[ -x cxxtest ]
./cxxtest
echo "run: OK"
