#------- Comment/uncomment the following line to enable/disable debugging---------
DEBUG 	= n

#---------------------- Change according to your files ----------------------------
SRC 	= i3ctransfer.c 			# Source File
TARGET 	= i3ctransfer				# Output file

CFLAGS += -I. -I./include/

include ${TOOLDIR}/rules/Rules.make.apps
#----------------------------------------------------------------------------------------

