#------- Comment/uncomment the following line to enable/disable debugging---------
DEBUG = n

#---------------------- Change according to your files ----------------------------
SRC = peci.c peci_cmds.c		# Source File
TARGET = peciapp 			# Output file

CFLAGS = -I${SPXINC}/linux

include ${TOOLDIR}/rules/Rules.make.apps

#----------------------------------------------------------------------------------------
