# This publication is intellectual property of Novell Inc. and Canonical
# Ltd. Its contents can be duplicated, either in part or in whole, provided
# that a copyright label is visibly located on each copy.
#
# All information found in this book has been compiled with utmost
# attention to detail. However, this does not guarantee complete accuracy.
# Neither SUSE LINUX GmbH, Canonical Ltd, the authors, nor the translators
# shall be held liable for possible errors or the consequences thereof.
#
# Many of the software and hardware descriptions cited in this book
# are registered trademarks. All trade names are subject to copyright
# restrictions and may be registered trade marks. SUSE LINUX GmbH
# and Canonical Ltd. essentially adhere to the manufacturer's spelling.
#
# Names of products and trademarks appearing in this book (with or without
# specific notation) are likewise subject to trademark and trade protection
# laws and may thus fall under copyright restrictions.
#


=pod

=head1 NAME

aa-autodep - guess basic AppArmor profile requirements

=head1 SYNOPSIS

B<aa-autodep I<E<lt>executableE<gt>> [I<E<lt>executableE<gt>> ...] [I<-d /path/to/profiles>] [I<-f>]>

=head1 OPTIONS

B<-d --dir  /path/to/profiles>

   Specifies where to look for the AppArmor security profile set.
   Defaults to /etc/apparmor.d.

B<-f --force>

   Overwrites any existing AppArmor profile for the executable with the generated minimal AppArmor profile.

=head1 DESCRIPTION

B<aa-autodep> is used to generate a minimal AppArmor profile for a set of
executables. This program will generate a profile for binary executable
as well as interpreted script programs. At a minimum aa-autodep will provide
a base profile containing a base include directive which includes basic
profile entries needed by most programs.  The profile is generated by
recursively calling ldd(1) on the executables listed on the command line.

The I<--force> option will overwrite any existing profile for the executable with
the newly generated minimal AppArmor profile.

=head1 BUGS

This program does not perform full static analysis of executables, so
the profiles generated are necessarily incomplete. If you find any bugs,
please report them at
L<https://bugs.launchpad.net/apparmor/+filebug>.

=head1 SEE ALSO

apparmor(7), apparmor.d(5), aa-complain(1), aa-enforce(1), aa-disable(1),
aa_change_hat(2), and L<https://wiki.apparmor.net>.

=cut
