#DEBUG = n

LIBRARY_NAME 	= libusbgadget_vnc

SRC 		= hid_vnc.c		 	# Source File

#----------------------------------------------------------------------------------------
include ${TOOLDIR}/rules/Rules.make.libs
