#!/bin/sh
# autopkgtest check: start a "simple" program and check that
# dynamic loading of modules works

set -e


WORKDIR=$(mktemp -d)
trap "rm -rf $WORKDIR" 0 INT QUIT ABRT PIPE TERM
cd $WORKDIR

echo "Running exexutable linked with libgcc and libstdc++ (apt)..."
if [ -x /usr/bin/apt ]; then
  apt=/usr/bin/apt
elif [ -x /bin/apt ]; then
  apt=/bin/apt
else
  echo "apt not found"
  exit 1
fi

ldd $apt
apt show libgcc1 libstdc++6

echo "Running dynamically linked executable (python3)..."
python3 -c 'print("Hello World!")'
echo "OK"

echo "Loading extension module..."
python3 -c 'import _hashlib; print(_hashlib.__dict__)'
echo "OK"
